In [7]:
import tensorflow as tf
hello = tf.constant("Hello, Tensorflow")
sess = tf.Session()
print(sess.run(hello))
sess.close()

Tensor("Const_8:0", shape=(), dtype=string)
b'Hello, Tensorflow'


In [6]:
import tensorflow as tf
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
sess = tf.Session()
print(sess.run(c))
sess.close()

42


In [20]:
import tensorflow as tf

X = tf.placeholder(tf.float32, [None, 3])
print(X)
#x_data = [[1, 1, 1], [1, 1, 1]]
x_data = [[1, 2, 3], [4, 5, 6]]

W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

expr = tf.matmul(X, W) + b

sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_Data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

Tensor("Placeholder_12:0", shape=(?, 3), dtype=float32)
=== x_Data ===
[[1, 1, 1], [1, 1, 1]]
=== W ===
[[ 1.2710398   0.96471953]
 [-1.0094863  -0.51838386]
 [-1.3314434   0.48874617]]
=== b ===
[[-0.9865026]
 [-0.4682494]]
=== expr ===
[[-2.0563924  -0.05142075]
 [-1.5381393   0.46683243]]


In [24]:
import tensorflow as tf

x_data = [1, 2, 3]
y_data = [1, 2, 3]

print(tf.random_uniform([1], -1.0, 1.0))

W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

hypothesis = W * X + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict= {X: x_data, Y: y_data})
        print(step, cost_val, sess.run(W), sess.run(b))
    print("\n=== Test ===")
    print("X : 5, Y : ", sess.run(hypothesis, feed_dict={X: 5}))
    print("X : 2.5, Y : ", sess.run(hypothesis, feed_dict={X: 2.5}))
        

Tensor("random_uniform_6:0", shape=(1,), dtype=float32)
0 1.4178772 [0.6894765] [0.83817685]
1 0.11142858 [0.6440277] [0.79475087]
2 0.0913344 [0.6583681] [0.7781896]
3 0.086819164 [0.6659487] [0.75920445]
4 0.08269306 [0.6740481] [0.7409841]
5 0.078765064 [0.6818763] [0.723168]
6 0.07502366 [0.68952453] [0.7057839]
7 0.071460016 [0.6969881] [0.6888173]
8 0.06806556 [0.70427233] [0.6722586]
9 0.06483238 [0.7113814] [0.65609795]
10 0.061752837 [0.7183196] [0.6403258]
11 0.05881952 [0.72509104] [0.62493277]
12 0.056025505 [0.73169965] [0.60990983]
13 0.053364303 [0.7381494] [0.595248]
14 0.05082943 [0.7444441] [0.58093864]
15 0.048415016 [0.7505875] [0.56697327]
16 0.04611525 [0.7565832] [0.5533436]
17 0.04392473 [0.7624348] [0.5400416]
18 0.04183827 [0.7681457] [0.5270594]
19 0.039850935 [0.7737193] [0.5143892]
20 0.037957992 [0.7791589] [0.50202364]
21 0.036154937 [0.7844678] [0.48995534]
22 0.034437537 [0.789649] [0.47817713]
23 0.032801744 [0.79470575] [0.4666821]
24 0.031243647 [0.7

In [ ]:
print ()