In [8]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
print("Your score : ", sess.run(hypothesis, feed_dict={X:[[100, 90, 80], [80, 90, 100]]}))

0 Cost:  249029.95 
Prediction:
 [[-310.99072]
 [-380.8872 ]
 [-371.39804]
 [-406.0728 ]
 [-291.1716 ]
 [-218.41254]
 [-304.68622]
 [-226.57483]
 [-359.7979 ]
 [-337.72607]
 [-294.03824]
 [-293.82144]
 [-382.07236]
 [-315.87708]
 [-307.36237]
 [-387.42673]
 [-301.10645]
 [-364.8059 ]
 [-362.9056 ]
 [-324.3412 ]
 [-357.55734]
 [-358.56824]
 [-339.85126]
 [-309.78735]
 [-392.76282]]
10 Cost:  53.463146 
Prediction:
 [[154.91331 ]
 [179.1258  ]
 [180.37056 ]
 [194.85756 ]
 [135.92903 ]
 [ 96.495224]
 [145.13878 ]
 [106.907486]
 [163.59851 ]
 [147.09747 ]
 [139.34377 ]
 [133.52449 ]
 [187.96883 ]
 [157.97882 ]
 [144.53752 ]
 [180.86304 ]
 [150.17607 ]
 [175.02678 ]
 [180.53908 ]
 [161.91032 ]
 [169.93503 ]
 [166.80878 ]
 [163.06429 ]
 [159.92685 ]
 [187.61382 ]]
20 Cost:  41.265224 
Prediction:
 [[158.10782]
 [183.00368]
 [184.17065]
 [199.0091 ]
 [138.88539]
 [ 98.6993 ]
 [148.25484]
 [109.22828]
 [167.2474 ]
 [150.5093 ]
 [142.34409]
 [136.50478]
 [191.88226]
 [161.21611]
 [147.67506]
 [

470 Cost:  29.680792 
Prediction:
 [[157.13252 ]
 [183.38708 ]
 [183.70346 ]
 [199.02841 ]
 [139.12868 ]
 [ 99.875336]
 [148.6182  ]
 [109.93942 ]
 [168.61185 ]
 [153.07962 ]
 [142.6155  ]
 [137.66133 ]
 [190.8862  ]
 [159.7375  ]
 [148.3309  ]
 [185.55566 ]
 [151.68866 ]
 [179.17474 ]
 [182.98888 ]
 [164.028   ]
 [174.05148 ]
 [171.23257 ]
 [166.69963 ]
 [160.93332 ]
 [191.52502 ]]
480 Cost:  29.472176 
Prediction:
 [[157.11258]
 [183.39413]
 [183.69354]
 [199.0282 ]
 [139.13301]
 [ 99.89852]
 [148.62509]
 [109.95349]
 [168.6386 ]
 [153.13058]
 [142.62051]
 [137.68402]
 [190.86566]
 [159.70735]
 [148.34366]
 [185.57005]
 [151.6567 ]
 [179.18254]
 [182.96283]
 [164.00327]
 [174.06027]
 [171.24754]
 [166.70236]
 [160.88908]
 [191.52246]]
490 Cost:  29.265432 
Prediction:
 [[157.09276 ]
 [183.40117 ]
 [183.68372 ]
 [199.02805 ]
 [139.13736 ]
 [ 99.921616]
 [148.632   ]
 [109.96753 ]
 [168.66522 ]
 [153.18135 ]
 [142.62553 ]
 [137.70667 ]
 [190.84525 ]
 [159.67737 ]
 [148.35637 ]
 [185.58

810 Cost:  23.529352 
Prediction:
 [[156.50363]
 [183.6092 ]
 [183.3908 ]
 [199.02351]
 [139.26419]
 [100.60738]
 [148.83923]
 [110.38851]
 [169.45638]
 [154.6912 ]
 [142.7753 ]
 [138.37914]
 [190.23674]
 [158.78342]
 [148.73619]
 [186.01059]
 [150.67595]
 [179.42538]
 [182.16573]
 [163.24654]
 [174.33168]
 [171.70596]
 [166.78818]
 [159.53526]
 [191.4436 ]]
820 Cost:  23.374998 
Prediction:
 [[156.48659]
 [183.61519]
 [183.3823 ]
 [199.02342]
 [139.2678 ]
 [100.62724]
 [148.8453 ]
 [110.40084]
 [169.47928]
 [154.73497]
 [142.77966]
 [138.39862]
 [190.21907]
 [158.75745]
 [148.74727]
 [186.02293]
 [150.64835]
 [179.4323 ]
 [182.14334]
 [163.22531]
 [174.33934]
 [171.71881]
 [166.79063]
 [159.49725]
 [191.44135]]
830 Cost:  23.221977 
Prediction:
 [[156.46959 ]
 [183.62114 ]
 [183.37384 ]
 [199.02328 ]
 [139.27138 ]
 [100.646996]
 [148.85135 ]
 [110.4131  ]
 [169.50208 ]
 [154.77855 ]
 [142.784   ]
 [138.41803 ]
 [190.20148 ]
 [158.73157 ]
 [148.75827 ]
 [186.0352  ]
 [150.62083 ]
 [179

1220 Cost:  18.19721 
Prediction:
 [[155.86462 ]
 [183.83221 ]
 [183.07162 ]
 [199.01979 ]
 [139.39684 ]
 [101.351524]
 [149.06973 ]
 [110.85622 ]
 [170.31482 ]
 [156.33505 ]
 [142.93962 ]
 [139.11032 ]
 [189.57234 ]
 [157.80598 ]
 [149.15382 ]
 [186.47308 ]
 [149.63506 ]
 [179.68953 ]
 [181.325   ]
 [162.44945 ]
 [174.62187 ]
 [172.18742 ]
 [166.88283 ]
 [158.10783 ]
 [191.35718 ]]
1230 Cost:  18.089811 
Prediction:
 [[155.8505 ]
 [183.8371 ]
 [183.06454]
 [199.01974]
 [139.3997 ]
 [101.368  ]
 [149.0749 ]
 [110.86672]
 [170.33382]
 [156.3715 ]
 [142.9433 ]
 [139.12653]
 [189.55759]
 [157.78426]
 [149.16315]
 [186.4833 ]
 [149.61188]
 [179.6955 ]
 [181.30637]
 [162.43178]
 [174.62837]
 [172.19809]
 [166.885  ]
 [158.07619]
 [191.35522]]
1240 Cost:  17.98331 
Prediction:
 [[155.83643]
 [183.84198]
 [183.05748]
 [199.01965]
 [139.40254]
 [101.38438]
 [149.08005]
 [110.87718]
 [170.35272]
 [156.40776]
 [142.94693]
 [139.14264]
 [189.54288]
 [157.7626 ]
 [149.17242]
 [186.4935 ]
 [149.588

1690 Cost:  14.047808 
Prediction:
 [[155.26582 ]
 [184.03798 ]
 [182.77074 ]
 [199.01778 ]
 [139.515   ]
 [102.049225]
 [149.2928  ]
 [111.30821 ]
 [171.11969 ]
 [157.88315 ]
 [143.09596 ]
 [139.79768 ]
 [188.9443  ]
 [156.88039 ]
 [149.55222 ]
 [186.90678 ]
 [148.6453  ]
 [179.9485  ]
 [180.53194 ]
 [161.69879 ]
 [174.90047 ]
 [172.63911 ]
 [166.97716 ]
 [156.76198 ]
 [191.27173 ]]
1700 Cost:  13.976902 
Prediction:
 [[155.25443]
 [184.04184]
 [182.76498]
 [199.01775]
 [139.51717]
 [102.06249]
 [149.2971 ]
 [111.31696]
 [171.13498]
 [157.91266]
 [143.09895]
 [139.81078]
 [188.9323 ]
 [156.86266]
 [149.55986]
 [186.91502]
 [148.6263 ]
 [179.95355]
 [180.5168 ]
 [161.68446]
 [174.90584]
 [172.6477 ]
 [166.97899]
 [156.73625]
 [191.27003]]
1710 Cost:  13.906612 
Prediction:
 [[155.24309 ]
 [184.0457  ]
 [182.75926 ]
 [199.01773 ]
 [139.51933 ]
 [102.0757  ]
 [149.30144 ]
 [111.325676]
 [171.15022 ]
 [157.94206 ]
 [143.10194 ]
 [139.82382 ]
 [188.92033 ]
 [156.84502 ]
 [149.56749 ]
 [186

In [11]:
import tensorflow as tf
import numpy as np

filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
coord.request_stop()
coord.join(threads)
        
print("Your score : ", sess.run(hypothesis, feed_dict={X:[[100, 90, 80], [80, 90, 100]]}))


0 Cost:  24673.545 
Prediction:
 [[ 5.8161173 ]
 [ 6.045392  ]
 [ 6.232209  ]
 [ 8.648332  ]
 [ 2.9699106 ]
 [ 5.208989  ]
 [ 9.706712  ]
 [11.683734  ]
 [ 7.8394365 ]
 [11.466916  ]
 [ 7.16129   ]
 [ 7.4414644 ]
 [ 4.437112  ]
 [ 0.98944175]
 [ 9.837743  ]
 [ 8.029035  ]
 [-1.6124374 ]
 [12.929612  ]
 [ 4.0802584 ]
 [ 4.152047  ]
 [10.477933  ]
 [ 7.6338396 ]
 [ 9.541177  ]
 [ 1.2699975 ]
 [ 5.46655   ]]
10 Cost:  9.219423 
Prediction:
 [[152.46355]
 [182.30469]
 [179.90219]
 [197.78596]
 [137.39874]
 [104.31487]
 [151.27892]
 [116.63118]
 [172.56427]
 [164.03766]
 [143.56177]
 [141.93553]
 [183.86447]
 [150.14937]
 [152.06084]
 [186.88846]
 [140.44623]
 [182.82812]
 [175.13852]
 [157.20775]
 [176.49495]
 [172.98642]
 [167.82571]
 [149.13083]
 [188.13953]]
20 Cost:  8.031959 
Prediction:
 [[153.47649]
 [183.5245 ]
 [181.10306]
 [199.09183]
 [138.3313 ]
 [104.9996 ]
 [152.25276]
 [117.348  ]
 [173.70241]
 [165.08768]
 [144.50278]
 [142.86366]
 [185.10722]
 [151.18546]
 [153.0393 ]
 [18

520 Cost:  7.592581 
Prediction:
 [[153.46753 ]
 [183.63297 ]
 [181.15604 ]
 [199.05893 ]
 [138.51814 ]
 [105.01094 ]
 [152.05948 ]
 [116.965515]
 [173.72044 ]
 [164.91438 ]
 [144.44518 ]
 [142.82455 ]
 [185.25731 ]
 [151.44818 ]
 [152.85286 ]
 [188.13672 ]
 [141.83348 ]
 [183.67834 ]
 [176.4624  ]
 [158.36218 ]
 [177.46092 ]
 [174.13406 ]
 [168.76282 ]
 [150.3681  ]
 [189.54103 ]]
530 Cost:  7.5850334 
Prediction:
 [[153.46713]
 [183.63489]
 [181.15681]
 [199.05812]
 [138.52155]
 [105.01118]
 [152.05576]
 [116.9583 ]
 [173.72075]
 [164.91122]
 [144.44397]
 [142.82379]
 [185.25986]
 [151.45282]
 [152.84929]
 [188.13684]
 [141.84067]
 [183.67227]
 [176.46474]
 [158.36371]
 [177.45747]
 [174.13406]
 [168.75981]
 [150.37173]
 [189.54343]]
540 Cost:  7.5775175 
Prediction:
 [[153.46672 ]
 [183.6368  ]
 [181.15761 ]
 [199.05734 ]
 [138.52496 ]
 [105.01141 ]
 [152.05203 ]
 [116.951096]
 [173.72107 ]
 [164.90808 ]
 [144.44281 ]
 [142.82306 ]
 [185.26244 ]
 [151.45749 ]
 [152.84573 ]
 [188.137

940 Cost:  7.309988 
Prediction:
 [[153.449  ]
 [183.71048]
 [181.18639]
 [199.02731]
 [138.65523]
 [105.0234 ]
 [151.91122]
 [116.6786 ]
 [173.73674]
 [164.79506]
 [144.39853]
 [142.79764]
 [185.35707]
 [151.6306 ]
 [152.71164]
 [188.14435]
 [142.11685]
 [183.43655]
 [176.55244]
 [158.42009]
 [177.3246 ]
 [174.13698]
 [168.64287]
 [150.50723]
 [189.63644]]
950 Cost:  7.304047 
Prediction:
 [[153.44852]
 [183.71227]
 [181.18704]
 [199.02661]
 [138.65834]
 [105.02375]
 [151.90791]
 [116.67215]
 [173.7372 ]
 [164.79254]
 [144.3975 ]
 [142.79712]
 [185.35925]
 [151.63463]
 [152.7085 ]
 [188.14458]
 [142.12317]
 [183.43112]
 [176.5544 ]
 [158.42133]
 [177.32155]
 [174.1371 ]
 [168.64017]
 [150.51024]
 [189.63861]]
960 Cost:  7.2981386 
Prediction:
 [[153.44803]
 [183.71405]
 [181.18771]
 [199.02588]
 [138.66144]
 [105.02411]
 [151.90459]
 [116.66573]
 [173.73766]
 [164.79002]
 [144.39648]
 [142.79659]
 [185.36143]
 [151.63864]
 [152.70535]
 [188.1448 ]
 [142.12944]
 [183.4257 ]
 [176.55634

1400 Cost:  7.0687394 
Prediction:
 [[153.42526 ]
 [183.78883 ]
 [181.2136  ]
 [198.99615 ]
 [138.79147 ]
 [105.042046]
 [151.76707 ]
 [116.399765]
 [173.7602  ]
 [164.69162 ]
 [144.35399 ]
 [142.7774  ]
 [185.4497  ]
 [151.802   ]
 [152.57602 ]
 [188.15588 ]
 [142.38722 ]
 [183.20052 ]
 [176.63399 ]
 [158.4703  ]
 [177.19275 ]
 [174.14401 ]
 [168.52545 ]
 [150.6321  ]
 [189.72978 ]]
1410 Cost:  7.0641437 
Prediction:
 [[153.42473]
 [183.79045]
 [181.21413]
 [198.99551]
 [138.7943 ]
 [105.04248]
 [151.76414]
 [116.39407]
 [173.76076]
 [164.68964]
 [144.3531 ]
 [142.77705]
 [185.45155]
 [151.80545]
 [152.57327]
 [188.15617]
 [142.39268]
 [183.1957 ]
 [176.63559]
 [158.47127]
 [177.19006]
 [174.14421]
 [168.52306]
 [150.63454]
 [189.7317 ]]
1420 Cost:  7.0595818 
Prediction:
 [[153.42416 ]
 [183.79208 ]
 [181.21465 ]
 [198.99486 ]
 [138.79709 ]
 [105.04293 ]
 [151.76122 ]
 [116.388405]
 [173.7613  ]
 [164.68767 ]
 [144.35219 ]
 [142.7767  ]
 [185.45337 ]
 [151.80887 ]
 [152.57051 ]
 [188

1890 Cost:  6.8714733 
Prediction:
 [[153.39758 ]
 [183.86507 ]
 [181.23691 ]
 [198.9665  ]
 [138.922   ]
 [105.06565 ]
 [151.63193 ]
 [116.138504]
 [173.78935 ]
 [164.60643 ]
 [144.31296 ]
 [142.76399 ]
 [185.53244 ]
 [151.95708 ]
 [152.45047 ]
 [188.17056 ]
 [142.63582 ]
 [182.97833 ]
 [176.70476 ]
 [158.51164 ]
 [177.06976 ]
 [174.15456 ]
 [168.41463 ]
 [150.73933 ]
 [189.8178  ]]
1900 Cost:  6.867985 
Prediction:
 [[153.39699]
 [183.86653]
 [181.23732]
 [198.96594]
 [138.92451]
 [105.06616]
 [151.62935]
 [116.13352]
 [173.78998]
 [164.60492]
 [144.31218]
 [142.76378]
 [185.53395]
 [151.95998]
 [152.44809]
 [188.17087]
 [142.6405 ]
 [182.97408]
 [176.70604]
 [158.51237]
 [177.06743]
 [174.1548 ]
 [168.41249]
 [150.74127]
 [189.81947]]
1910 Cost:  6.8645086 
Prediction:
 [[153.39641]
 [183.86801]
 [181.23775]
 [198.96536]
 [138.92702]
 [105.06667]
 [151.62677]
 [116.12855]
 [173.7906 ]
 [164.60342]
 [144.3114 ]
 [142.7636 ]
 [185.53549]
 [151.96286]
 [152.44571]
 [188.17117]
 [142.64