In [37]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [38]:
# 1D Array
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t.ndim) # rank
print(t.shape) # shape
print(t[0])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])
print(t[:])

1
(7,)
0.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]
[0. 1. 2. 3. 4. 5. 6.]


In [39]:
# 2D Array
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t.ndim)
print(t.shape)

2
(4, 3)


In [40]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval()

array([4], dtype=int32)

In [41]:
t = tf.constant([[1, 2], [3, 4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [14]:
# axis = 0, 1, ... 안쪽으로 들어가며 올라감

array([[5., 5.]], dtype=float32)

In [42]:
mat1 = tf.constant([[3., 3.]])
mat2 = tf.constant([[2., 2.]])
(mat1 + mat2).eval()

array([[5., 5.]], dtype=float32)

In [43]:
# Broadcasting : Shape 이 달라도 계산해줌
mat1 = tf.constant([[3., 3.]])
mat2 = tf.constant([2., 2.])
(mat1 + mat2).eval()

array([[5., 5.]], dtype=float32)

In [44]:
# Broadcasting : Shape 이 달라도 계산해줌
mat1 = tf.constant([[3., 3.]])
mat2 = tf.constant([[2.], [2.]])
(mat1 + mat2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [45]:
# Reduce mean : 평균 구하기
# Reduce sum : 합계 구하기
# int
tf.reduce_mean([1, 2], axis=0).eval()

1

In [46]:
# float
tf.reduce_mean([[1., 2.], [3., 4.]]).eval()

2.5

In [47]:
# axis = 0
tf.reduce_mean([[1., 2.], [3., 4.]], axis=0).eval()

array([2., 3.], dtype=float32)

In [48]:
# axis = 1
tf.reduce_mean([[1., 2.], [3., 4.]], axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [49]:
# axis = -1 (가장 큰 axis 지정)
tf.reduce_mean([[1., 2.], [3., 4.]], axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [50]:
# argmax : 가장 큰 값의 index 구하기
x = [[0, 1, 2], 
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [51]:
# axis = 1
tf.argmax(x, axis=1).eval()

array([2, 0])

In [52]:
# Reshape
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [58]:
# axis 1 은 3으로
# axis 0 은 합침
# (4, 3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
# (4, 1, 3)
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [62]:
# Squeeze
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2], dtype=int32)

In [63]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

In [64]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [75]:
# depth = class 수
# lank 가 하나 늘어나게 됨
tf.one_hot([0, 1, 2, 9], depth=10).eval()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [77]:
# 늘어난 lank reshape
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [78]:
# casting
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [79]:
# ex. true 인거 갯수 세고 싶을 때 casting 하고 sum
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

In [80]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [82]:
tf.stack([x, y, z], axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [83]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [84]:
# 동일 Shape 에 1 로 채워진 array 만들기
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [86]:
# 동일 Shape 에 0 으로 채워진 array 만들기
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [89]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [90]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
